// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA4lRhWya0vj422cRQyoTeROkWbuUA9o0',
    appId: '1:721687862384:web:3a6cdc2f104a3476cda8b5',
    messagingSenderId: '721687862384',
    projectId: 'tourmate-b25c4',
    authDomain: 'tourmate-b25c4.firebaseapp.com',
    storageBucket: 'tourmate-b25c4.appspot.com',
    measurementId: 'G-1ZC5PV5R3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_0hw4FkzTM60q-bGHQsXI_1dpTDcizSg',
    appId: '1:721687862384:android:318bc248c1cd50fecda8b5',
    messagingSenderId: '721687862384',
    projectId: 'tourmate-b25c4',
    storageBucket: 'tourmate-b25c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8are8tVI2u3FUKoPKlqaA_N-roZACYMg',
    appId: '1:721687862384:ios:ae9fe27f168c5381cda8b5',
    messagingSenderId: '721687862384',
    projectId: 'tourmate-b25c4',
    storageBucket: 'tourmate-b25c4.appspot.com',
    iosBundleId: 'com.example.tourMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8are8tVI2u3FUKoPKlqaA_N-roZACYMg',
    appId: '1:721687862384:ios:7de7b20efe5c143dcda8b5',
    messagingSenderId: '721687862384',
    projectId: 'tourmate-b25c4',
    storageBucket: 'tourmate-b25c4.appspot.com',
    iosBundleId: 'com.example.tourMate.RunnerTests',
  );
}
